### ISSUE TITLE
Cowboy version not available

### ISSUE THREAD

**Issue by olafura** [ninenines/farwest_demo#1]
I'm getting
```
===> Failed to solve release:
 Dependency cowboy is specified as a dependency but is not reachable by the system.
```

**Comment by essen** [comment]
Oh yeah guess I gotta depend on it explicitly for now.

**Comment by essen** [comment]
Done, please fetch and try again!

**Comment by olafura** [comment]
That works now I just have to update the version of Erlang I'm using :D

**Comment by essen** [comment]
Cheers. Thanks for testing! Hope you won't mind the complete lack of CSS at the moment. :-)

**Comment by olafura** [comment]
Works well, CSS isn't the most important thing in the beginning.

**Comment by essen** [comment]
Yes my main goal is to have the client side of things work and use it to write all sorts of automated tests.
